### ISSUE TITLE
Translations ?

### ISSUE THREAD

**Issue by lutinotmalin** [a-dekker/Unit-Converter#1]
Hi !

I'm a Sailfish OS user and the fork you made for Unit Converter has already been very useful to me. Many thanks for that !

However, I regret that I have to use it in English. The app is already perfectly usable but would be more comfortable if I could use it in my main language. My question is : are you planning to get through localizations, here on GitHub or Transifex ? If so, I would love to be part of it and finally use Unit Converter in French.

Best regards,

lutinotmalin

**Comment by a-dekker** [comment]
Hi!

A translation is going to be quite a challenge. The main elements are easy to translate (and can already be translated), but all of the units are hidden in arrays, and I have no idea how hard is would be to make them translatable.

**Comment by lutinotmalin** [comment]
Oh I see... Unhappily I'm not able to help you with that arrays, don't have the skills at all.

Maybe letting this issue open could lead, one day, to someone who's got the solution ?

**Comment by a-dekker** [comment]
Don't hold your breath for anyone helping out.
I might do some tests, see how difficult it could be.

**Comment by a-dekker** [comment]
I added a translation file and did a dutch translation of that. The units still remain troublesome. The categories on the main page for example are a reference to other parts of the code, and if you translate them, it breaks.
You can decide for yourself if you want to translate the part that can be translated for now, or are only interested if the whole app can be fully translated.

**Comment by lutinotmalin** [comment]
OK, thanks for that !

I'ill have a look in the next days, and I think I'll translate the already translatable content, even if it's not complete !

Cheers !

**Comment by lutinotmalin** [comment]
Days became weeks but the translation is finally ready ! :+1: 

Best regards,

lutinotmalin

**Comment by dikonov** [comment]
The common i10n technique for such cases is to uses whatever strings exist internally but substitute them just before presenting to the user. The UI always knows what element is tapped or ativated, so its human label is not relevant.  Why could it not be implemented here?

**Comment by a-dekker** [comment]
I never stated this could not be implemented. Only that it is a challenge. If you are up to it, be my guest.

**Comment by dikonov** [comment]
Could you point me to a tutorial for a sailfish equivalent of gettext? It's a pity that SFOS chose to depart from standards and use weird wayland and ui libs...

**Comment by a-dekker** [comment]
SailfishOS is Qt based, so a search on "Internationalization with Qt" might help.
