### ISSUE TITLE
Can't update currency information

### ISSUE THREAD

**Issue by Pohli** [a-dekker/Unit-Converter#11]
As already mentioned in #9 currency update doesn't work even after deleting the conf file. I set Unit Converter to update at app start. Then I installed new version and copied console output:

    [nemo@Sailfish ~]$ harbour-unitconverter
    [D] unknown:0 - Sending request for xml
    [D] unknown:0 - Using Wayland-EGL
    [W] unknown:0 - Could not find any zN.M subdirs!
    [W] unknown:0 - Theme dir "/usr/share/themes/jolla-ambient/meegotouch/z1.0/" does not exist
    [D] onStatusChanged:95 - Loading...
    [W] unknown:0 - Error while downloading xml: "SSL handshake failed"
    [W] unknown:0 - void CurrencyCache::showNotification(QString, QString)

**Comment by a-dekker** [comment]
That sounds like an TLS issue and could mean your certificates are not up-to-date.
Could you try if `curl -O "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml"` works on the phone?

**Comment by Pohli** [comment]
Edited my previous post but I don't have text formatting here.

    [nemo@Sailfish ~]$ curl -O "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml"
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current  Dload  Upload   Total   Spent    Left  Speed
    100  1665    0  1665    0     0   7270      0 --:--:-- --:--:-- --:--:--  7270

**Comment by a-dekker** [comment]
And does the downloaded file `eurofxref-daily.xml` contain currency rate data?

**Comment by Pohli** [comment]
Yes, do you need the file?
Sorry, didn't know what "curl" is for, that it downloads something.

**Comment by a-dekker** [comment]
So if you do a `cat eurofxref-daily.xml` it shows data like: 

`<Cube currency='CAD' rate='1.5602'/>`

If so, retrieving the data seems not to be an issue.

**Comment by Pohli** [comment]
Yes, it does contain currency data.

**Comment by a-dekker** [comment]
I know I had SSL issues on my Jolla 1 with Unitconverter. But I had been playing with the trusted certifcates myself, so I blamed it on that. After updating the truststore with as far as I can remember cert data from my Xperia, all worked fine.
But as far as I remember the curl did also not work, although I am not 100% sure.
Updating the trust store might be a bit risky, so let's not go on that path. For now I am out of ideas, maybe something pops up later.

**Comment by a-dekker** [comment]
If you go through Settings > Certificates ->  TLS Certificates, then search for "Entrust".
Do you find 4 certificates? And if you click on them for details, is the current date for all of them between NotAfter and Notbefore?

**Comment by Pohli** [comment]
Yes, all four dates are correct.

Btw: do you know the tags for preformatted text or code text here for this Github comment field?

Edit: Found out, four spaces in the beginning of every line, any other?

**Comment by dikonov** [comment]
I got the same issue after updating the package. I have never touched any certificates. The current date  and all 4 certificate dates are OK.

**Comment by a-dekker** [comment]
There is a comment on openrepos.net which may be of help: https://openrepos.net/comment/31017#comment-31017
