### ISSUE TITLE
Some digits are missing at the ruler scales

### ISSUE THREAD

**Issue by dikonov** [a-dekker/Unit-Converter#5]
The ruler scales are right size on Jolla C now, but the extended portions of the scales have no digits.
The longer side has 1-9 but the palces for 10,11,12 are empty.
The shorter scale lacks 6 and 7.

**Comment by a-dekker** [comment]
The numbering is based on the Jolla 1 resolution. On the tablet even more numbers are not mentioned of course.

**Comment by a-dekker** [comment]
Fixed in 2-16.1
