### ISSUE TITLE
Cannot input cyrillic letters in the search field

### ISSUE THREAD

**Issue by dikonov** [a-dekker/Unit-Converter#6]
When the Russian translation becomes complete it will be necessary to be able to search by Russian names of units and currencies. Currently it is impossible to enter any non-latin letters in the search field.

Even when I type in English, tapping on the found items does nothing. It should probly open the relevant unit category page.

**Comment by a-dekker** [comment]
Tapping on a searched item never had any effect in my experience. Never looked at it further.

**Comment by a-dekker** [comment]
Had a closer look at the Quick search page. The idea is to type (the first part of) the category. Then the related units show up. After that tap the unit what will have the value "1". Tap another unit, and the (quick) conversion will show on the screen.

**Comment by Pohli** [comment]
There should be some hints then. I think almost nobody will find out how to use Quick Search without those.

**Comment by a-dekker** [comment]
Added help page for Quick Search in commit 32bac062a94a1d74f9331179959c366677e6f91e

**Comment by Pohli** [comment]
I can't find the help page.

Anyway an interactive help would be much better I think but also means much more effort, doesn't it?

**Comment by a-dekker** [comment]
There is a help page as pulldown menu on the Quick Search page. And indeed this was the option with minimum effort.

**Comment by Pohli** [comment]
Ah okay. It's confusing that the narrow coloured line which indicates the pulley menu is not at the uppermost rim. I can attach screenshots as soon as I'll get to my laptop.

**Comment by a-dekker** [comment]
No need of a screenshot, I know what you mean. Already made a small change for that.

**Comment by a-dekker** [comment]
As there are no plans for translation support for this part the issue is not relevant here.
