### ISSUE TITLE
Update currency cache unresponsive

### ISSUE THREAD

**Issue by Pohli** [a-dekker/Unit-Converter#9]
If I tap the Update currency cache button on the Options page there's no feedback if update has been successful or not.

BTW: For me currency update never worked so far IIRC.

Jolla Phone with SFOS 3.0.0.8 and Unit Converter 2.17

**Comment by a-dekker** [comment]
I have chosen a weekly currency update. Just checked and it updated by itself without any issues.

You could remove the file `/home/nemo/.config/harbour-unitconverter/harbour-unitconverter.conf` and see if you can update your currency rates afterwards.

It does not inform you about ((un)successful) updates that have taken place. I could have a look at that.

**Comment by a-dekker** [comment]
Should be changed in commit 32bac062a94a1d74f9331179959c366677e6f91e

**Comment by Pohli** [comment]
What is changed? Only notification I guess. I'll open another issue.
Notification works in new version.
